In [1]:
import pandas as pd # shift + enter : run 

In [2]:
import numpy as np # 통계 관련 패키지
                   #.ipynp : 노트북 형식의 저장

In [3]:
s = pd.Series([1,2,3,4,5]) # R에서 C함수

In [4]:
s # print(s)와 동일

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
pd.date_range('2013-01-03', periods=6) # CPU에서 처리
dates = pd.date_range('2013-01-03', periods=6) # RAM에 저장 

In [6]:
dates # dtype = [ns] : 숫자로 인식

DatetimeIndex(['2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06',
               '2013-01-07', '2013-01-08'],
              dtype='datetime64[ns]', freq='D')

In [7]:
np.random.randn(1,2)

array([[-0.53117813,  1.42690168]])

In [8]:
np.random.randn(6,2)

array([[ 1.87830209,  0.05347748],
       [ 0.14911467,  0.15352306],
       [ 1.4932447 ,  1.26436979],
       [ 0.18708203,  0.34650108],
       [-0.05365815, -1.04383508],
       [-1.38782622,  0.22492428]])

In [9]:
np.random.randn(6,4)

array([[-0.40895618,  0.8673859 , -0.6678851 , -1.34156809],
       [ 0.48125502,  0.13105332,  1.31087233,  0.79630714],
       [-0.08283941, -0.54435986,  0.15405686,  1.46774683],
       [ 0.39134922,  1.59082005,  0.77064212, -0.34226489],
       [-0.16535042, -0.10153607,  0.4104453 ,  1.10016501],
       [-0.4824367 ,  0.15030817,  1.33831522,  0.2456012 ]])

In [12]:
df = pd.DataFrame(np.random.randn(6,4), index = dates, columns = ['A','B','C','D'])

In [13]:
df

A         B         C         D
2013-01-03 -0.369422 -0.187873  0.692741  1.419638
2013-01-04 -1.132413 -0.950777 -0.559406 -0.650706
2013-01-05 -0.396961 -0.940127  0.311955 -1.759480
2013-01-06 -1.101775 -1.112993  0.527831  0.538167
2013-01-07  0.039350  1.391830 -0.444905  2.327442
2013-01-08 -1.287794  0.204903  1.908725  0.635815

In [16]:
df.head(3)

A         B         C         D
2013-01-03 -0.369422 -0.187873  0.692741  1.419638
2013-01-04 -1.132413 -0.950777 -0.559406 -0.650706
2013-01-05 -0.396961 -0.940127  0.311955 -1.759480

In [17]:
df.index

DatetimeIndex(['2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06',
               '2013-01-07', '2013-01-08'],
              dtype='datetime64[ns]', freq='D')

In [18]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [19]:
df.values

array([[-0.36942209, -0.18787287,  0.69274106,  1.41963779],
       [-1.13241285, -0.95077669, -0.55940608, -0.65070621],
       [-0.39696127, -0.94012661,  0.31195524, -1.75948012],
       [-1.10177481, -1.11299272,  0.52783091,  0.53816684],
       [ 0.03935028,  1.39183041, -0.44490534,  2.32744216],
       [-1.28779439,  0.20490335,  1.9087255 ,  0.63581528]])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-03 to 2013-01-08
Freq: D
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [21]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.708169 -0.265839  0.406157  0.418479
std    0.536891  0.960939  0.896676  1.455657
min   -1.287794 -1.112993 -0.559406 -1.759480
25%   -1.124753 -0.948114 -0.255690 -0.353488
50%   -0.749368 -0.564000  0.419893  0.586991
75%   -0.376307  0.106709  0.651514  1.223682
max    0.039350  1.391830  1.908725  2.327442

In [22]:
df.sort_values(by = 'B', ascending = False) # default : 오름차순 (ascending)

A         B         C         D
2013-01-07  0.039350  1.391830 -0.444905  2.327442
2013-01-08 -1.287794  0.204903  1.908725  0.635815
2013-01-03 -0.369422 -0.187873  0.692741  1.419638
2013-01-05 -0.396961 -0.940127  0.311955 -1.759480
2013-01-04 -1.132413 -0.950777 -0.559406 -0.650706
2013-01-06 -1.101775 -1.112993  0.527831  0.538167

In [23]:
df['A']

2013-01-03   -0.369422
2013-01-04   -1.132413
2013-01-05   -0.396961
2013-01-06   -1.101775
2013-01-07    0.039350
2013-01-08   -1.287794
Freq: D, Name: A, dtype: float64

In [24]:
df[0:3]

A         B         C         D
2013-01-03 -0.369422 -0.187873  0.692741  1.419638
2013-01-04 -1.132413 -0.950777 -0.559406 -0.650706
2013-01-05 -0.396961 -0.940127  0.311955 -1.759480